const ACCESS_TOKEN = 'DQVJzcFFlNnk0TDlvMTh3TU1ZAWEoyT1hEeEduVGxHTE9wVks0WVdwMTZAieE15V0tQOEFGYlJCUWhrSDl2cGxIRzliOTRZAbUFHR05uU2ViY1BOQWpEb28zMVBrLUdlNVRkMEVFcV9xQWI1V21HVnFva2plellKUFN0TDdQSTY4QWRaZAUM4R3M0MjJscUMxZAmhNV2tfcHAwaFJMSDJpQ0l5MmtHV3E1QW1CS051aktZAR3JjcFpubzlfLU44czBhMVdHSklKZATBR';
const APP_ID = process.env.APP_ID;
const APP_SECRET = process.env.APP_SECRET;
const VERIFY_TOKEN = 'VyBlNCwUj5pckEqYGY5PCY6N35kcSNFbWMaDpVVGZqUWdxXw==TUBPcCV4Kj5VYXI8NUgyPWM0cVd3WHppYF0pOCosYV4ubE1nXw';
const SERVER_URL = process.env.SERVER_URL;

module.exports = {
  ACCESS_TOKEN,
  APP_ID,
  APP_SECRET,
  VERIFY_TOKEN,
  SERVER_URL,
};
